CI: use public runners for cargo features check (#2727)
* CI: use public runners for cargo features check

This isn't a very important job and it's not required to merge so it's
IMO fine if it's a bit slower. This frees up buildjet runners for other
jobs.

* CI: somewhat strangely, we run out of disk space

* CI: delete less

Currently seems to delete something we need.

    --- stderr
    sqlite3/sqlite3.h:35:10: fatal error: 'stdarg.h' file not found